### PR TITLE
Feat overload `setCoefficient`

### PR DESCRIPTION
**Pull request by sahilbhola14**
Added the overloaded setCoefficient which adds the capability of setting multiple coefficients at once

### CODE REVIEW

**Comment by sahilbhola14** [comment]
After rebasing my branch with the main the tests seems to fail. I am not sure if the definition of all the tests are complete.

**Comment by ArshSaja** [comment]
> After rebasing my branch with the main the tests seems to fail. I am not sure if the definition of all the tests are complete. @bkochuna @KyleVaughn

Is it working before ?

**Comment by A-CGray** [comment]
@sahilbhola14 it seems like there are a bunch of changes from other PR's that have gotten combined in with this one, I think it might be best to close this PR and create another one starting clean from the current main branch

**Comment by ArshSaja** [comment]
@sahilbhola14  can you make a new PR for your changes. So that it can be checked easily

**Comment by sahilbhola14** [comment]
@ArshSaja I just did. Check out #85

**Pull request closed without merging**
