### PR TITLE
Implement getFormat in Formatter interface

### LINKED ISSUE #18: Design Template for getFormat
## Background
Explain why this issue was created/needed

We need to construct a design pattern and simplify the complexity of the interface by reducing the number of conversions between different formats.

## Tasks
Describe what work is expected to be performed as a part of this issue

Apply design patterns by constructing UML diagrams by producing class, sequence, state, and communication diagrams

## Definition of Done
Describe acceptance criteria for the issue

- [x] produce UML diagrams that outline the interface
- [x] having a working implementation high-level design

### PR DESCRIPTION
**Pull request by mahletm-777**
This is to implement the high-level design of the getFormat interface. Completion of this PR will resolves #18

### CODE REVIEW

**Comment by umichyujl** [comment]
What do I need to do here?

**Comment by mahletm-777** [comment]
@umichyujl can you implement your getFormat code using the Formatter.hpp interface

**Comment by umichyujl** [comment]
> @umichyujl can you implement your getFormat code using the Formatter.hpp interface

I can not find a Formatter.hpp interface in the JDS and DEN folders

**Comment by Connor1476** [comment]
Just found it in the Formatter branch in src/.

**Comment by A-CGray** [comment]
@mahletm-777 This PR is trying to merge code from main into your Formatter branch, is that correct?

**Comment by A-CGray** [comment]
In that case, you'll need to close this PR and re-open it with the branches the right way around

**Comment by mahletm-777** [comment]
Will do. Thanks for letting me know

**Comment by mahletm-777** [comment]
@umichyujl @ShiboTan @Connor1476 The header files are now updated in the Formatter branch. Could you guys fill in your individual components within Formatter.hpp.

**Comment by umichyujl** [comment]
> @umichyujl @ShiboTan @Connor1476 The header files are now updated in the Formatter branch. Could you guys fill in your individual components within Formatter.hpp.

I think I have already put my part in this file yesterday. Can't you see the previous version of it?

**Comment by umichyujl** [comment]
> @umichyujl @ShiboTan @Connor1476 The header files are now updated in the Formatter branch. Could you guys fill in your individual components within Formatter.hpp.

Oh I think we might have some unpushed codes so you did not see it. Never mind, I pushed my part just now, you can take a look. If there's any issue with compiling please let me know.

**Comment by ShiboTan** [comment]
I just pushed my codes to COO and ELL.

**Pull request closed without merging**
