### PR TITLE
Add formatting and linting via pre-commit

### LINKED ISSUE #57: Implemented automated formatting/linting for commits
## Background
To facilitate developer effectiveness across large projects it is helpful to have some standardized formatting guidelines.

Requiring all your developers to know these guidelines explicitly and remember to follow them is time consuming and error prone.

Reformatting code to some style guide is a good task to be automated in the workflow.

There are several ways this can be done, but ideally, you want it to be done before a commit is executed. Additionally, you want the reformatting to not require any additional actions on the part of the developer, nor do you want it to pull in any major dependencies or require a complex setup on the part of a new developer, or when switching to a new machine for development.

## Tasks
- [ ] Identify appropriate mechanisms for scripting pre-commit reformatting
- [ ] Implement the pre-commit formatting
- [ ] (Optional) provide some capability to test this workflow.

## Definition of Done
The above tasks are completed, if possible this workflow feature is tested. Code is reviewed by an instructor.

### PR DESCRIPTION
**Pull request by A-CGray**
Closes #57 

This PR adds formatting and linting checks using pre-commit. When you install pre-commit locally, all your commits will be checked before they are pushed so that you can only push correctly formatted code.

I have also added a GitHub action that runs the pre-commit checks on PR's so we can be sure all merged PR's match the repo's formatting and linting standards.

For now, I have commented out the clang-tidy check, it currently fails because the repo doesn't contain working code, this should be uncommented once the code is considered functional.

I have also added a top-level readme to the repo with instructions for setting up pre-commit

### CODE REVIEW

**Comment by A-CGray** [comment]
@bkochuna is this the kind of system you were thinking of for #57 ?

**Comment by bkochuna** [comment]
I was actually thinking of using the git hooks.

It looks like 

> @bkochuna is this the kind of system you were thinking of for #57 ?

Pretty close. I would have done or tried a few other things.
1. I would have tried to put together fairly extensive documentation on what the formatting guidelines are. e.g. what are the rules/guidelines/conventions that are being applied?
2. I would have tried to implement this with [native git hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) rather than whatever sorcery you have conjured up here. I *think* with native git hooks, anyone using git anywhere on any machine will have pre-commit hook run by git. No extra commands to run. No waiting until code is pushed to github to have the formatting script run.

I would say spend 15-30 minutes to see if there's a way to have your formatting stuff get run as a git hook.

**Comment by A-CGray** [comment]
[pre-commit](https://pre-commit.com/) uses native git-hooks, it just makes it much easier to setup and maintain them. As I wrote in the readme, once you run `pre-commit install` locally, all the hooks (including formatting) will be run locally whenever you try to commit. I just added the GitHub action to catch the edge case where someone has not setup the hooks on their local machine.

I can write a bit of documentation about what all the hooks do. Do you need me to document all of the clang-format settings though?

**Comment by bkochuna** [comment]
> [pre-commit](https://pre-commit.com/) uses native git-hooks, it just makes it much easier to setup and maintain them. As I wrote in the readme, once you run `pre-commit install` locally, all the hooks (including formatting) will be run locally whenever you try to commit. I just added the GitHub action to catch the edge case where someone has not setup the hooks on their local machine.
> 
> I can write a bit of documentation about what all the hooks do. Do you need me to document all of the clang-format settings though?

That sounds awesome, and I cloned the branch to test this out, but I think its still a bit clunky. I think its clunky because to use this feature you must:
1. Have a working python and pip installation
2. Have the pre-commit python package installed
3. Run the `pre-commit install` command for each time you clone the repo and potentially run steps to install python, pip, and pre-commit each time you are on a new machine.

Here is the pre-commit hook that the `$ pre-commit install` generated for me:
```
#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
# ID: 138fd403232d2ddd5efb44317e38bf03

# start templated
INSTALL_PYTHON=/sw/pkgs/arc/python3.9-anaconda/2021.11/bin/python
ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)
# end templated

HERE="$(cd "$(dirname "$0")" && pwd)"
ARGS+=(--hook-dir "$HERE" -- "$@")

if [ -x "$INSTALL_PYTHON" ]; then
    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
elif command -v pre-commit > /dev/null; then
    exec pre-commit "${ARGS[@]}"
else
    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
    exit 1
fi
```

What I was hoping would be possible is that you could just commit a pre-commit hook file in the git repo and upload it, and there would be no additional setup steps for new dependencies or installing anything for new developers. You just clone the repo and there's already a `.git/hooks/pre-commit` file. No additional setup necessary.

However, I think to do this, the pre-commit script would basically have to be a bash/shell script. A quick perusing of the pre-commit website didn't reveal that there was a way to use the python `pre-commit` package to generate a git pre-commit hook that does not rely on a specific python installation.

**Comment by bkochuna** [comment]
I'd say I'd give t his 15/20 in terms of points. It is pretty easy to use, but it could be seamless. You could also try modfiying the CMake build system to assert that python is required for configuring and create a custom CMake target that will install the git pre-commit hook. 

So the first time someone tries to configure the project with Cmake, the hook is automatically installed.

**Review by bkochuna — APPROVED** [review]
This looks fine for me. A full shell based linter that doesn't have external dependencies could be added later, but this helps in its current state.

**Comment by A-CGray** [comment]
> I'd say I'd give t his 15/20 in terms of points. It is pretty easy to use, but it could be seamless. You could also try modfiying the CMake build system to assert that python is required for configuring and create a custom CMake target that will install the git pre-commit hook.
> 
> So the first time someone tries to configure the project with Cmake, the hook is automatically installed.
I think this is done now

> 
> Edit: Using Cmake I would give 3 more points to automating the install. Full 5 points if the whole can be made to work in a shell script without using external software that does not come normally installed on Linux.

I will push back a bit here and say that I actually think that using pre-commit makes things far easier from a dependency standpoint. If we wanted to use native git-hooks then we'd need to worry about all the dependencies for every hook separately. For example, clang-format does not come automatically installed on all linux distros, so I'd need to write a shell script to install it on the user's machine when they build the project, but then I'd also need to figure out what distro they're using so I know what command to install it with, and then I also can't guarantee that the version of clang-format I want to use is going to be available on that distro.

On the other hand, with pre-commit, the only dependency is python 3, and that is guaranteed to be available on all but the most ancient of distros. pre-commit sets up an environment for each hook with all the necessary dependencies so we can be sure that the hooks running on people's machines are going to be identical to those that run on the GitHub action.

**Pull request merged**
