### PR TITLE
Overloaded constructor - den

### PR DESCRIPTION
**Pull request by tcoonsUM**
Adds overloaded constructor for DEN format

### CODE REVIEW

**Review by Connor1476 — COMMENTED** [review]
The overload constructor looks good, but I don't see any unit tests for it... In the email sent out today it seemed liked that was a requirement, but am would need to confirm.

**Comment by tcoonsUM** [comment]
> The overload constructor looks good, but I don't see any unit tests for it... In the email sent out today it seemed liked that was a requirement, but would need to confirm.

I agree, just added a testing file and unit test. @Connor1476

**Comment by tcoonsUM** [comment]
@Connor1476 just fixed some issues with allocating memory for the 2D array. Could we review this ASAP so that it is merged to DEN before DEN is merged to MAIN?

**Comment by Connor1476** [comment]
Yes! Looking at it now

**Comment by tcoonsUM** [comment]
> Yes! Looking at it now

Thank you @Connor1476 🤝

**Pull request merged**
