### PR TITLE
Install target cmake

### PR DESCRIPTION
**Pull request by meichenl95**
Modifications on CMakeLists.txt.

### CODE REVIEW

**Comment by A-CGray** [comment]
Hey @meichenl95 , does this compile correctly for you? I am getting this error:

```
CMake Error at CMakeLists.txt:16 (set_target_properties):
  set_target_properties Can not find target to add properties to: SpMV


CMake Error at CMakeLists.txt:19 (install):
  install TARGETS given target "SpMV" which does not exist.
```

I think the issue is that you are trying to call `set_target_properties`, but you haven't defined the `SpMV` target anywhere.

How is this build process supposed to work since we only have header files?

**Comment by meichenl95** [comment]
> Hey @meichenl95 , does this compile correctly for you? I am getting this error:
> 
> ```
> CMake Error at CMakeLists.txt:16 (set_target_properties):
>   set_target_properties Can not find target to add properties to: SpMV
> 
> 
> CMake Error at CMakeLists.txt:19 (install):
>   install TARGETS given target "SpMV" which does not exist.
> ```
> 
> I think the issue is that you are trying to call `set_target_properties`, but you haven't defined the `SpMV` target anywhere.
> 
> How is this build process supposed to work since we only have header files?

It works on my computer:
[meichenl@gl-login2 ners570f22-SpMV]$ cmake .
...
Requirement already satisfied: typing-extensions>=3.6.4; python_version < "3.8" in /home/meichenl/.local/lib/python3.6/site-packages (from importlib-metadata; python_version < "3.8"->pre-commit)
pre-commit installed at .git/hooks/pre-commit
-- Configuring done
-- Generating done
-- Build files have been written to: /home/meichenl/Documents/NERS570/ners570f22-SpMV

I think the SpMV is defined as the library when we add library in src/CMakeLists.txt?

**Comment by A-CGray** [comment]
Can you merge the main branch with this one, I just added a GitHub action that will try running the cmake build and the tests so we can see if it works on a different computer

**Comment by meichenl95** [comment]
Sure. Can you approve the review? At least 1 approving review is required to merge to the main branch.

**Comment by A-CGray** [comment]
No sorry, I meant the other way round, merge the recent changes from the main branch into the install-cmake-target branch, then we can check if the build runs correctly, and if it does I will approve this PR to merge the install-cmake-target branch into main

**Comment by meichenl95** [comment]
Okay. I can have a try now.

**Comment by meichenl95** [comment]
Here's what I got.

[meichenl@gl-login2 ners570f22-SpMV]$ cmake .
-- The C compiler identification is GNU 8.4.1
-- The CXX compiler identification is GNU 8.4.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python: /usr/bin/python3.6 (found version "3.6.8") found components: Interpreter 
Requirement already satisfied: pre-commit in /home/meichenl/.local/lib/python3.6/site-packages
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /home/meichenl/.local/lib/python3.6/site-packages (from pre-commit)
Requirement already satisfied: identify>=1.0.0 in /home/meichenl/.local/lib/python3.6/site-packages (from pre-commit)
Requirement already satisfied: virtualenv>=20.0.8 in /home/meichenl/.local/lib/python3.6/site-packages (from pre-commit)
Requirement already satisfied: toml in /home/meichenl/.local/lib/python3.6/site-packages (from pre-commit)
Requirement already satisfied: nodeenv>=0.11.1 in /home/meichenl/.local/lib/python3.6/site-packages (from pre-commit)
Requirement already satisfied: importlib-resources<5.3; python_version < "3.7" in /home/meichenl/.local/lib/python3.6/site-packages (from pre-commit)
Requirement already satisfied: pyyaml>=5.1 in /home/meichenl/.local/lib/python3.6/site-packages (from pre-commit)
Requirement already satisfied: cfgv>=2.0.0 in /home/meichenl/.local/lib/python3.6/site-packages (from pre-commit)
Requirement already satisfied: zipp>=0.5 in /home/meichenl/.local/lib/python3.6/site-packages (from importlib-metadata; python_version < "3.8"->pre-commit)
Requirement already satisfied: typing-extensions>=3.6.4; python_version < "3.8" in /home/meichenl/.local/lib/python3.6/site-packages (from importlib-metadata; python_version < "3.8"->pre-commit)
Requirement already satisfied: platformdirs<3,>=2.4 in /home/meichenl/.local/lib/python3.6/site-packages (from virtualenv>=20.0.8->pre-commit)
Requirement already satisfied: distlib<1,>=0.3.6 in /home/meichenl/.local/lib/python3.6/site-packages (from virtualenv>=20.0.8->pre-commit)
Requirement already satisfied: filelock<4,>=3.4.1 in /home/meichenl/.local/lib/python3.6/site-packages (from virtualenv>=20.0.8->pre-commit)
pre-commit installed at .git/hooks/pre-commit
-- Configuring done
-- Generating done
-- Build files have been written to: /home/meichenl/Documents/NERS570/ners570f22-SpMV

**Comment by A-CGray** [comment]
This is after doing the merge? It looks good, can you do a `git push` so that the changes show up on this PR?

**Review by A-CGray — APPROVED** [review]
The compilation is failing but that seems to be because there is some incorrect code in the DEN matrix class which is not your problem, good work!

**Comment by SoumiKDaS1701** [comment]
Hey Alasdair,

   I did the unassemble and destructor for DEN, if you find anything
obviously wrong, let me know.

--Soumik

Soumik Das
Ph.D. student, Zimmerman Group
Department of Chemistry, University of Michigan
930 N. University Ave., Ann Arbor, MI 48109 USA

**Comment by SoumiKDaS1701** [comment]
I think someone updated the getFormat() in DEN branch, but after it was
merged to main. I think that now it looks fine. I'll create another pull
request.

--Soumik

Soumik Das
Ph.D. student, Zimmerman Group
Department of Chemistry, University of Michigan
930 N. University Ave., Ann Arbor, MI 48109 USA

**Pull request merged**
